[package]
name = "kv-log"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version ="1", features = ["derive"]}
serde_json = "1.0.140"
tokio = {version ="1.46.1", features = ["full"]}
trait-variant = "0.1.2"


[dev-dependencies]
tempfile ="3.20.0"
rand = "0.9.1"

